fixtures:
  symlinks:
    confluence: "#{source_dir}"
  repositories:
    deploy: "http://github.com/mkrakowitzer/puppet-deploy"
    staging: "http://github.com/nanliu/puppet-staging"
    stdlib: "http://github.com/puppetlabs/puppetlabs-stdlib.git"
