fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    deploy: "https://github.com/mkrakowitzer/puppet-deploy.git"
    staging: "https://github.com/nanliu/puppet-staging.git"
  symlinks:
    confluence: "#{source_dir}"
